#!/bin/bash

# In the name of God
# This code is public domain

if [ $# -lt 1 ]
then
	echo "Usage: `basename $0` cable1.html [cable2.html ...]" >&2
	exit 1
fi

export LANG=
export LC_LANG=
export LC_LOCALE=

EXCLUDE_FILE="`dirname $0`/exclude.txt"

contents=`mktemp`
trap "rm $contents" EXIT TERM INT

for cable in "$@"
do
	grep '<pre>' "$cable" | tail -n 1 >>"$contents"
done

sed 's!</\?[^>]*>\([^<]*\)!\L\1!g' -i "$contents"		# Strip HTML tags and convert to lowercase
#sed 's/c o n f i d e n t i a l/confidential/g' -i "$contents"
#sed 's/s e c r e t/secret/g' -i "$contents"
sed 's/[^a-z]\+/\n/g' -i "$contents"		# Convert all non-alphabetic character sequences into new lines
sed '/^\s*$/d' -i "$contents"		# Remove empty lines
exclude_regex="\\<(`tr '\\n' '|' <\"$EXCLUDE_FILE\"`[a-z])\\>"		# Exclude words in exclude file and single-letter words
sort "$contents" | uniq -c | grep -Ev "$exclude_regex" | sort -nrk1,1		# Count words and produce output sorted by count
